root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/" # Changed: specify main.go explicitly
delay = 300
exclude_dir = [
  "assets",
  "tmp",
  "vendor",
  "testdata",
  "node_modules",
  "internal/sqlc/_old",
  "internal/sqlc/_notyet",
  "ui/_old_js",
]
include_ext = ["go", "templ"]
exclude_regex = ["_test.go"]
exclude_file = []
include_dir = []
include_file = []
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
pre_cmd = []
post_cmd = []
send_interrupt = true
stop_on_error = false
kill_delay = "500ms"

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true
